# Generated by Django 3.2 on 2022-08-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='mouth_to_learn',
            new_name='mouths_to_learn',
        ),
    ]
